"""The per-project configuration flow-review writes on first run and reads forever after.

v2 schema (A-4). The version gate exists because a config generated by an older skill and read
by a newer one is the drift case nobody notices: every field still parses, and one rule
silently means something else. Refusing a NEWER schema is the direction that matters -- an old
skill cannot know what a field added later means.

Unknown-key errors are friendly by design (A-4): every rejected key names the valid set and, via
difflib, its closest match, because the reader is a person editing this file by hand or a v1
config walking through A3's auto-migration, not a machine that already knows the schema.
"""
from __future__ import annotations

import difflib
import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

SCHEMA_VERSION = 2
VALID_KINDS = ("ui", "cli", "api", "library")
VALID_PROVENANCE = ("audited", "proven", "user")
VALID_DRIVERS = ("cdp", "playwright", "adb", "ios-sim", "shell", "http", "custom", "pending")
VALID_STATE = ("disposable", "persistent")
VALID_MODEL_PROFILE = ("lean", "default", "max")
VALID_ROLES = ("explorer", "replay-repair", "lens", "cold-eyes", "triage", "verifier")
VALID_ROLE_MODELS = ("haiku", "sonnet", "opus")

WEB_OPTION_KEYS = (
    "base_url", "health_path", "ready_timeout_s", "exit_timeout_s", "viewport", "tokens_file",
)

_SURFACE_KEYS = {
    "id", "name", "kind", "driver", "launch", "cwd", "env", "options", "preconditions",
    "state", "reset", "creds", "record", "provenance", "declined",
}
_CONFIG_KEYS = {
    "schema_version", "generator_version", "surfaces", "model_profile", "role_overrides",
    "budget", "test_inbox", "flows_hash",
}
_PRECONDITION_KEYS = {"name", "cmd"}


class ConfigVersionError(Exception):
    """The config on disk was written by a newer flow-review than this one."""


class ConfigKeyError(ValueError):
    def __init__(self, key: str, valid_keys, where: str):
        self.key = key
        self.valid_keys = tuple(valid_keys)
        self.where = where
        self.closest = difflib.get_close_matches(key, self.valid_keys, n=1)
        message = (
            f"unknown key {key!r} at {where}; "
            f"valid keys are: {', '.join(self.valid_keys) if self.valid_keys else '(none)'}."
        )
        if self.closest:
            message += f" Did you mean {self.closest[0]!r}?"
        super().__init__(message)


def _check_keys(data: dict, allowed: set[str], where: str) -> None:
    for key in data:
        if key not in allowed:
            raise ConfigKeyError(key, sorted(allowed), where)


@dataclass
class Surface:
    id: str
    name: str
    kind: str
    driver: str
    launch: str
    cwd: str = "."
    env: dict[str, str] = field(default_factory=dict)
    options: dict = field(default_factory=dict)
    preconditions: list[dict] = field(default_factory=list)
    state: str = "disposable"
    reset: str | None = None
    creds: dict[str, str] = field(default_factory=dict)
    record: bool = False
    provenance: dict[str, str] = field(default_factory=dict)
    declined: bool = False


@dataclass
class Config:
    schema_version: int
    generator_version: str
    surfaces: list[Surface] = field(default_factory=list)
    model_profile: str = "default"
    role_overrides: dict[str, str] = field(default_factory=dict)
    budget: dict = field(default_factory=lambda: {"cap_tokens": None})
    test_inbox: dict | None = None
    flows_hash: str = ""


def validate_preconditions(preconditions) -> None:
    if not isinstance(preconditions, list):
        raise ValueError(f"preconditions must be a list, got {type(preconditions).__name__}")
    for index, item in enumerate(preconditions):
        if not isinstance(item, dict):
            raise ValueError(f"preconditions[{index}] must be an object")
        if "cmd" not in item:
            raise ValueError(f"preconditions[{index}] is missing required key 'cmd'")
        _check_keys(item, _PRECONDITION_KEYS, f"preconditions[{index}]")


def _validate_options(surface: Surface) -> None:
    where = f"surfaces[{surface.id!r}].options"
    if surface.driver == "playwright":
        _check_keys(surface.options, set(WEB_OPTION_KEYS), where)
    elif surface.options:
        _check_keys(surface.options, set(), where)


def _validate_surface(surface: Surface) -> None:
    if surface.kind not in VALID_KINDS:
        raise ValueError(
            f"surface {surface.id!r} has unknown kind {surface.kind!r}; expected one of {VALID_KINDS}"
        )
    if surface.driver not in VALID_DRIVERS:
        raise ValueError(
            f"surface {surface.id!r} has unknown driver {surface.driver!r}; expected one of {VALID_DRIVERS}"
        )
    if surface.state not in VALID_STATE:
        raise ValueError(
            f"surface {surface.id!r} has unknown state {surface.state!r}; expected one of {VALID_STATE}"
        )
    for key, value in surface.provenance.items():
        if value not in VALID_PROVENANCE:
            raise ValueError(
                f"surface {surface.id!r} field {key!r} has unknown provenance {value!r}; "
                f"expected one of {VALID_PROVENANCE}"
            )
    validate_preconditions(surface.preconditions)
    _validate_options(surface)


def _validate(cfg: Config) -> None:
    if cfg.model_profile not in VALID_MODEL_PROFILE:
        raise ValueError(
            f"model_profile {cfg.model_profile!r} is unknown; expected one of {VALID_MODEL_PROFILE}"
        )
    for role, model in cfg.role_overrides.items():
        if role not in VALID_ROLES:
            raise ValueError(f"role_overrides has unknown role {role!r}; expected one of {VALID_ROLES}")
        if model not in VALID_ROLE_MODELS:
            raise ValueError(
                f"role_overrides[{role!r}] has unknown model {model!r}; "
                f"expected one of {VALID_ROLE_MODELS}"
            )
    ids = [s.id for s in cfg.surfaces]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        raise ValueError(f"surface id(s) reused across surfaces: {sorted(dupes)}")
    for surface in cfg.surfaces:
        _validate_surface(surface)


def _surface_from_raw(entry, index: int) -> Surface:
    if not isinstance(entry, dict):
        raise ValueError(f"surface at index {index} is not an object")
    name = entry.get("id") or entry.get("name")
    where = f"surfaces[{index}]" + (f" ({name!r})" if name else "")
    _check_keys(entry, _SURFACE_KEYS, where)
    try:
        return Surface(**entry)
    except TypeError as exc:
        raise ValueError(f"surface at {where} is malformed: {exc}") from exc


def load(path: Path) -> Config:
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    found = raw.get("schema_version", 0)
    if found > SCHEMA_VERSION:
        raise ConfigVersionError(
            f"{path} was written by a newer flow-review (schema {found} > {SCHEMA_VERSION}). "
            "Update the plugin rather than editing the file."
        )
    _check_keys(raw, _CONFIG_KEYS, "config")
    surfaces = [_surface_from_raw(entry, i) for i, entry in enumerate(raw.get("surfaces", []))]
    cfg = Config(
        schema_version=SCHEMA_VERSION,
        generator_version=raw.get("generator_version", ""),
        surfaces=surfaces,
        model_profile=raw.get("model_profile", "default"),
        role_overrides=raw.get("role_overrides", {}),
        budget=raw.get("budget", {"cap_tokens": None}),
        test_inbox=raw.get("test_inbox"),
        flows_hash=raw.get("flows_hash", ""),
    )
    _validate(cfg)
    return cfg


def save(cfg: Config, path: Path) -> None:
    _validate(cfg)
    text = json.dumps(asdict(cfg), indent=2, ensure_ascii=True) + "\n"
    Path(path).write_text(text, encoding="utf-8")
