"""The per-project configuration flow-review writes on first run and reads forever after.

The version gate exists because a config generated by an older skill and read by a newer one
is the drift case nobody notices: every field still parses, and one rule silently means
something else. Refusing a NEWER schema is the direction that matters -- an old skill cannot
know what a field added later means.
"""
from __future__ import annotations

import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCHEMA_VERSION = 1
VALID_KINDS = ("ui", "cli", "api", "library")
VALID_PROVENANCE = ("audited", "proven", "user")
VALID_DRIVERS = ("cdp", "playwright", "adb", "ios-sim", "shell", "http", "custom")


class ConfigVersionError(Exception):
    """The config on disk was written by a newer flow-review than this one."""


@dataclass
class Surface:
    name: str
    kind: str
    driver: str
    launch: str
    preconditions: list[dict] = field(default_factory=list)
    destructive: bool = False
    provenance: dict[str, str] = field(default_factory=dict)


@dataclass
class Config:
    schema_version: int
    # The flow-review plugin version that wrote this config -- the "version" string
    # from the plugin's own plugin.json, read fresh at setup time, never cached.
    # Provenance for debugging ("which generator produced this file"), not a gate:
    # schema_version is what load() refuses on, this field only informs.
    generator_version: str
    surfaces: list[Surface] = field(default_factory=list)
    lens_sets: dict[str, list[str]] = field(default_factory=dict)
    tester_agent: str = "general-purpose"
    evidence_types: list[str] = field(default_factory=list)
    flows_hash: str = ""


def _validate(cfg: Config) -> None:
    for surface in cfg.surfaces:
        if surface.kind not in VALID_KINDS:
            raise ValueError(
                f"surface {surface.name!r} has unknown kind {surface.kind!r}; "
                f"expected one of {VALID_KINDS}"
            )
        if surface.driver not in VALID_DRIVERS:
            raise ValueError(
                f"surface {surface.name!r} has unknown driver {surface.driver!r}; "
                f"expected one of {VALID_DRIVERS}"
            )
        for key, value in surface.provenance.items():
            if value not in VALID_PROVENANCE:
                raise ValueError(
                    f"surface {surface.name!r} field {key!r} has unknown provenance "
                    f"{value!r}; expected one of {VALID_PROVENANCE}"
                )


def load(path: Path) -> Config:
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    found = raw.get("schema_version", 0)
    if found > SCHEMA_VERSION:
        raise ConfigVersionError(
            f"{path} was written by a newer flow-review (schema {found} > {SCHEMA_VERSION}). "
            "Update the plugin rather than editing the file."
        )
    surfaces = []
    for index, entry in enumerate(raw.get("surfaces", [])):
        try:
            surfaces.append(Surface(**entry))
        except TypeError as exc:
            name = entry.get("name") if isinstance(entry, dict) else None
            identifier = f"index {index}, name {name!r}" if name else f"index {index}"
            raise ValueError(
                f"surface at {identifier} in {path} is malformed: {exc}"
            ) from exc
    # A config from an older schema is rewritten in full by the next save(), so the
    # object this call returns already carries the CURRENT schema version -- the code
    # that just parsed it is what now vouches for its shape. `found` above is only ever
    # the version the newer-schema gate compares against.
    cfg = Config(
        schema_version=SCHEMA_VERSION,
        generator_version=raw.get("generator_version", ""),
        surfaces=surfaces,
        lens_sets=raw.get("lens_sets", {}),
        tester_agent=raw.get("tester_agent", "general-purpose"),
        evidence_types=raw.get("evidence_types", []),
        flows_hash=raw.get("flows_hash", ""),
    )
    _validate(cfg)
    return cfg


def save(cfg: Config, path: Path) -> None:
    # A Config built in memory and saved straight to disk never passed through load()'s
    # validation, so save() has to run the same check -- otherwise the bad value ships
    # to disk and the failure surfaces later, in another process, unlinked from its cause.
    _validate(cfg)
    # ponytail: indent=2 + trailing newline, because a human hand-edits this file
    text = json.dumps(asdict(cfg), indent=2, ensure_ascii=True) + "\n"
    Path(path).write_text(text, encoding="utf-8")
